format = """
$directory\
$git_branch\
$git_state\
$git_status\
$aws\
$character"""
add_newline = false

[directory]
style = "fg:cyan"
read_only_style = "fg:cyan"
truncation_length = 3
truncation_symbol = "…/"
format = "[ $path]($style)[$read_only]($read_only_style) "

[git_branch]
style = "fg:green"
symbol = " "
format = "[$symbol$branch(:$remote_branch)]($style) "
truncation_length = 24
truncation_symbol = "…"

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"

[aws]
symbol = ""
style = "fg:yellow"
format = '[$symbol$profile]($style) '
force_display = false

[time]
disabled = false
time_format = "%R"
format = " $time "
