_G.Config.leader_clues = {
  { mode = 'n', keys = '<leader>l', desc = '+Language' },
  { mode = 'n', keys = '<leader>f', desc = '+Find' },
}

local pick = require('mini.pick')
local extra = require('mini.extra')

vim.keymap.set('n', '<leader>la', vim.lsp.buf.code_action, { desc = 'Actions' })
vim.keymap.set('n', '<leader>ld', function()
  require('mini.extra').pickers.lsp({ scope = 'definition' })
end, { desc = 'Definition' })
vim.keymap.set('n', '<leader>lD', function()
  require('mini.extra').pickers.lsp({ scope = 'declaration' })
end, { desc = 'Declaration' })
vim.keymap.set('n', '<leader>lf', function()
  require('conform').format()
end, { desc = 'Format' })
vim.keymap.set('n', '<leader>li', function()
  require('mini.extra').pickers.lsp({ scope = 'implementation' })
end, { desc = 'Implementation' })
vim.keymap.set('n', '<leader>lr', function()
  require('mini.extra').pickers.lsp({ scope = 'references' })
end, { desc = 'References' })
vim.keymap.set('n', '<leader>lO', function()
  require('mini.extra').pickers.lsp({ scope = 'document_symbol' })
end, { desc = 'Document symbols' })
vim.keymap.set('n', '<leader>lW', function()
  require('mini.extra').pickers.lsp({ scope = 'workspace_symbol_live' })
end, { desc = 'Workspace symbols' })
vim.keymap.set('n', '<leader>lt', function()
  require('mini.extra').pickers.lsp({ scope = 'type_definition' })
end, { desc = 'Type definition' })
vim.keymap.set('n', '<leader>le', function()
  require('mini.extra').pickers.diagnostic()
end, { desc = 'Diagnostics' })
vim.keymap.set('n', '<leader>lq', function()
  require('mini.extra').pickers.list({ scope = 'quickfix' })
end, { desc = 'Quickfix' })

vim.keymap.set('n', '<leader>ff', pick.builtin.files, { desc = 'Files' })
vim.keymap.set('n', '<leader>fg', pick.builtin.grep_live, { desc = 'Grep live' })
vim.keymap.set('n', '<leader>fb', pick.builtin.buffers, { desc = 'Buffers' })
vim.keymap.set('n', '<leader>fh', pick.builtin.help, { desc = 'Help' })
vim.keymap.set('n', '<leader>fr', pick.builtin.resume, { desc = 'Resume' })
vim.keymap.set('n', '<leader>fo', function()
  extra.pickers.oldfiles({ current_dir = true })
end, { desc = 'Old files (cwd)' })
