os:
  editPreset: nvim
git:
  overrideGpg: true
  diffRenderers:
    - command: difft --color=always --display=inline --syntax-highlight=off
      type: extDiff
    - command: difft --color=always --display=side-by-side --syntax-highlight=off
      type: extDiff
