# vim:ft=kitty

## name: nvim-light
## author: nshern
## upstream: https://raw.githubusercontent.com/nshern/neovim-default-colorscheme-extras/refs/heads/main/extras/alacritty/nvim-light.toml

foreground #14161b
background #e0e2ea
selection_foreground #14161b
selection_background #2c2e33

cursor #14161b
cursor_text_color #e0e2ea

url_color #004c63

active_tab_background #c4c6cd
active_tab_foreground #14161b
inactive_tab_background #e0e2ea
inactive_tab_foreground #4f5258
tab_bar_background #e0e2ea
tab_bar_margin_color none

# normal
color0 #c4c6cd
color1 #590008
color2 #005523
color3 #6b5300
color4 #004c63
color5 #470045
color6 #007373
color7 #2c2e33

# bright
color8 #9b9ea4
color9 #640009
color10 #006029
color11 #765d00
color12 #005574
color13 #52004f
color14 #008080
color15 #4f5258
color16 #007373
color17 #4f5258
