# vim:ft=kitty

## name: nvim-light
## author: nshern
## upstream: https://raw.githubusercontent.com/nshern/neovim-default-colorscheme-extras/refs/heads/main/extras/alacritty/nvim-light.toml

foreground #14161b
background #E0E2EA
selection_foreground #14161b
selection_background #C4C6CD

cursor #14161b
cursor_text_color #E0E2EA

url_color #004c63

active_tab_background #E0E2EA
active_tab_foreground #14161b
inactive_tab_background #C4C6CD
inactive_tab_foreground #2c2e33

# normal
color0 #C4C6CD
color1 #590008
color2 #005523
color3 #6b5300
color4 #004c63
color5 #470045
color6 #007373
color7 #2c2e33

# bright
color8 #9b9ea4
color9 #640009
color10 #006029
color11 #765d00
color12 #005574
color13 #52004f
color14 #008080
color15 #4f5258
