# vim:ft=kitty

## name: nvim-dark
## author: nshern
## upstream: https://raw.githubusercontent.com/nshern/neovim-default-colorscheme-extras/refs/heads/main/extras/alacritty/nvim-dark.toml

foreground #e0e2ea
background #14161b
selection_foreground #e0e2ea
selection_background #4f5258

cursor #e0e2ea
cursor_text_color #14161b

url_color #95c5e5

active_tab_background #95c5e5
active_tab_foreground #14161b
inactive_tab_background #14161b
inactive_tab_foreground #c4c6cd
tab_bar_background #14161b
tab_bar_margin_color none

# normal
color0 #2c2e33
color1 #e5adb9
color2 #a2dfc0
color3 #e3ca85
color4 #95c5e5
color5 #e5b6e6
color6 #7edfde
color7 #c4c6cd

# bright
color8 #4f5258
color9 #ffc0b9
color10 #b4f6c0
color11 #fce094
color12 #a6dbff
color13 #ffcaff
color14 #8cf8f7
color15 #9b9ea4
