# Environment
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
export STARSHIP_CONFIG="$XDG_CONFIG_HOME/starship/starship.toml"

typeset -U path
path=("$HOME/.cargo/bin" "$HOME/.grok/bin" $path)

# History
HISTFILE="$XDG_STATE_HOME/zsh/history"
HISTSIZE=100000
SAVEHIST=100000
setopt EXTENDED_HISTORY HIST_IGNORE_ALL_DUPS HIST_REDUCE_BLANKS SHARE_HISTORY

# Completion
autoload -Uz compinit edit-command-line
mkdir -p "${HISTFILE:h}" "$XDG_CACHE_HOME/zsh" 2>/dev/null
compinit -d "$XDG_CACHE_HOME/zsh/compdump"

# Line editor
bindkey -e
zle -N edit-command-line
bindkey '^X^E' edit-command-line

# Tools
(( $+commands[tv] )) && source "$XDG_CONFIG_HOME/television/shell/integration.zsh"
(( $+commands[starship] )) && eval "$(starship init zsh)"
(( $+commands[zoxide] )) && eval "$(zoxide init zsh)"

# Aliases
alias v="nvim"
alias g="lazygit"
alias k="kubectl"
alias ls="eza"
alias lt="eza --tree --level=2"
